In [1]:
import torch
import torch.nn as nn

In [3]:
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size
S = 30      # Target sequence length of longest target in batch
S_min = 10  # Minimum target length, for demonstration purposes

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()

print(input)

tensor([[[-3.8177, -3.4990, -4.4691,  ..., -3.5495, -4.1650, -2.5304],
         [-3.1624, -2.4659, -2.9950,  ..., -2.8206, -4.1718, -2.2872],
         [-4.4344, -2.4153, -3.8925,  ..., -2.1291, -3.0468, -1.7685],
         ...,
         [-2.6247, -3.2221, -4.1532,  ..., -3.4086, -3.1485, -2.6316],
         [-3.4904, -3.6862, -3.6181,  ..., -4.2120, -2.5961, -2.5689],
         [-3.6710, -4.3676, -1.1697,  ..., -2.6758, -4.0635, -3.8582]],

        [[-2.1092, -2.7072, -5.2090,  ..., -3.5453, -2.6835, -2.8505],
         [-3.4936, -3.1420, -3.6757,  ..., -2.4405, -3.6277, -3.2602],
         [-5.3820, -3.8148, -4.4921,  ..., -2.8791, -3.4138, -4.8301],
         ...,
         [-3.9751, -4.9870, -1.6331,  ..., -3.8222, -3.3409, -2.0731],
         [-2.4160, -3.8831, -4.1845,  ..., -3.4716, -3.1904, -2.6512],
         [-2.2395, -3.7096, -3.5285,  ..., -5.5746, -3.9016, -3.0046]],

        [[-4.9522, -4.5762, -3.2803,  ..., -2.4808, -3.5877, -3.3120],
         [-3.2018, -2.2764, -4.4012,  ..., -3

In [4]:
# Initialize random batch of targets (0 = blank, 1:C = classes)
target = torch.randint(low=1, high=C, size=(N, S), dtype=torch.long)

print(target)

tensor([[15, 17,  4, 15,  7, 11,  9, 19, 18,  8,  6,  4, 18,  5,  3, 15, 14,  8,
          1, 12,  6, 19,  8, 12,  7, 10,  4, 17, 15, 18],
        [ 4, 14, 16,  5, 17, 18, 14,  2, 14,  6,  1,  9, 13,  8, 10,  4,  6,  4,
         12,  9,  4, 15, 11, 14, 16,  7, 16,  7, 15,  1],
        [ 4,  8, 17,  7,  3, 15, 16, 13,  4,  5,  8, 18,  1,  6,  5,  5, 16,  3,
         12, 11, 10,  7,  6,  6, 11, 13,  7,  7,  3,  2],
        [ 6, 10,  4, 10, 12, 15, 15,  8,  4,  7, 12,  5,  2,  5,  6, 14,  8, 14,
          2,  1, 15, 17,  3,  9,  5,  8,  2, 11, 16,  2],
        [10, 14,  7,  2,  7, 12, 17,  6,  1,  7, 13,  9,  2, 12, 13, 16,  6, 12,
         17,  4,  7, 11, 12,  8, 14,  9, 19, 15,  5, 12],
        [ 2,  4,  2, 11, 16, 17, 14, 18, 15, 14, 13,  2, 12, 12, 16, 10,  1, 13,
         14,  4, 14,  4, 13,  5, 17,  7, 13,  9,  2,  6],
        [ 8,  8, 11, 17,  2,  5, 13,  5,  1, 17, 12, 17, 10, 17,  4, 18, 13, 12,
         18, 18, 14, 13, 19,  8, 19, 11,  8, 18,  3, 16],
        [12, 11,  9,  7,  2

In [5]:
input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)
print(input_lengths)

tensor([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])


In [6]:
target_lengths = torch.randint(low=S_min, high=S, size=(N,), dtype=torch.long)
print(target_lengths)

tensor([19, 20, 20, 16, 27, 24, 28, 13, 13, 29, 21, 18, 25, 10, 16, 13])


In [7]:
ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
print(loss)
loss.backward()

tensor(6.5718, grad_fn=<MeanBackward1>)
